version: "3.5"
services:
  kenya_county:
    image: dnjau/kenya_county_image:latest
    ports:
      - "8085:8085"
    volumes:
      - .:/kenya_county_javabackend
    deploy:
      update_config:
        parallelism: 1
        max_failure_ratio: 0
        delay: 3s
        failure_action: rollback
      restart_policy:
        max_attempts: 3
        condition: on-failure
      replicas: 3
      placement:
        constraints: [ node.role == manager ]
    networks:
      - kenya_county_network
networks:
  kenya_county_network:
    external: true
